[build]
command="netlify-extension build -a"
environment = { EXTENSION_ENABLED = "true" }

[functions]
directory = "src/endpoints"

[dev]
command = "netlify-extension dev"

[[plugins]]
package = "@netlify/netlify-plugin-netlify-extension"